
const $=(s,r=document)=>r.querySelector(s);
async function api(p,o={}){ const r=await fetch(p,Object.assign({headers:{'Content-Type':'application/json'}},o)); if(!r.ok) throw new Error(await r.text().catch(()=>r.statusText)); return r.json(); }
let CUR_UID=null;
document.addEventListener('DOMContentLoaded', async ()=>{ try{ const me=(await api('/api/me')).user; if(!me||!me.is_owner){ alert('للمالك فقط'); location.href='index.html'; return; } }catch{ location.href='index.html'; return; } $('#replySend').onclick=sendReply; $('#q').addEventListener('input', e=> loadThreads(e.target.value)); await loadThreads(); await loadUsers(); await loadSnips(); });
async function loadThreads(q=''){ const rows=await api('/api/admin/threads?q='+encodeURIComponent(q||'')); const root=$('#threads'); root.innerHTML=''; rows.forEach(t=>{ const d=document.createElement('div'); d.className='card'; d.style.margin='6px 0'; d.innerHTML=`<div><strong>${t.user_email||('user#'+t.user_id)}</strong></div><div class='small'>${t.last_body||''}</div>`; d.onclick=()=>openThread(t.user_id,t.user_email); root.appendChild(d); }); }
async function openThread(uid,email){ CUR_UID=uid; $('#convHeader').textContent='محادثة: '+(email||('user#'+uid)); const msgs=await api('/api/admin/thread/'+uid); const body=$('#convBody'); body.innerHTML=''; msgs.forEach(m=>{ const b=document.createElement('div'); b.className='chip'; b.style.display='block'; b.style.margin='6px 0'; b.style.background=m.from_owner?'#0d2b22':'#111522'; b.textContent=m.body; body.appendChild(b); }); body.scrollTop=body.scrollHeight; }
async function sendReply(){ const txt=($('#replyInput').value||'').trim(); if(!txt||!CUR_UID) return; await api('/api/admin/thread/'+CUR_UID+'/reply',{method:'POST',body:JSON.stringify({body:txt})}); $('#replyInput').value=''; await openThread(CUR_UID); }
async function loadUsers(){ const rows=await api('/api/admin/users'); const root=$('#users'); root.innerHTML=''; rows.forEach(u=>{ const d=document.createElement('div'); d.className='row'; d.style.justifyContent='space-between'; d.innerHTML=`<div><strong>${u.email}</strong><div class='small'>${u.name||''}</div></div>`; const btn=document.createElement('button'); btn.className='chip'; btn.textContent='حذف'; btn.onclick=async()=>{ if(!confirm('حذف المستخدم وكل بياناته؟')) return; await api('/api/admin/users/'+u.id,{method:'DELETE'}); await loadUsers(); await loadSnips(); }; d.appendChild(btn); root.appendChild(d); }); }
async function loadSnips(){ const rows=await api('/api/snippets'); const root=$('#snips'); root.innerHTML=''; rows.forEach(s=>{ const d=document.createElement('div'); d.className='row'; d.style.justifyContent='space-between'; d.innerHTML=`<div><strong>${s.title}</strong><div class='small'>${s.lang} · ${s.owner_email||'مجهول'}</div></div>`; const btn=document.createElement('button'); btn.className='chip'; btn.textContent='حذف'; btn.onclick=async()=>{ if(!confirm('حذف الكود؟')) return; await api('/api/snippets/'+s.id,{method:'DELETE'}); await loadSnips(); }; d.appendChild(btn); root.appendChild(d); }); }
